<?php

/**
 * Implements hook_perm();
 */
function coffee_permission() {
  return array(
    'access coffee' => array(
      'title' => t('Access Coffee'),
      'description' => t('Access the Coffee search box to navigate fast between admin pages'),
  ),
  );
}

/**
 * Implements hook_menu();
 */
function coffee_menu() {

  // define ajax callback for results
  $items['admin/coffee/result/%'] = array(
    'title' => 'Coffee Result Handler',
    'page callback' => 'coffee_result_handler',
    'page arguments' => array(3),
    'access arguments' => array('access coffee'),
    'type' => MENU_CALLBACK,
  );
  return $items;

}

/**
 * Handler for Coffee
 *
 * The coffee_result_hanlder will process the input
 * look for matches and returns a json encoded result that is used
 * to display the results.
 *
 * @param
 *    $input is used to build the query
 * @return
 *    json encoded output with results based on the $input
 */
function coffee_result_handler($input = FALSE) {

  // based on the first char coffee should handle a function callback
  // or the basic functionality (redirecting to paths)
  $action_trigger = ':';

  // if the $action_trigger is fired
  // invoke all implementations of hook_coffee_action()
  if (strstr(check_plain(urldecode($input)), $action_trigger)) {
    // execute action, invode hook_coffee
    foreach (module_implements('coffee_action') as $module) {
      $op = str_ireplace($action_trigger, '', $input);
      $result = module_invoke($module, 'coffee_action', $op);
    }
  }
  else {
    // is should fire the default implementation of Coffee
    // it invokes the coffee_redirect function to look in the menu_links table
    $result = coffee_redirect($input);
  }

  if (!empty($result)) {
    // return should be in json format so the JavaScript can handle it
    print json_encode($result);
  }
  drupal_exit();

}

/**
 * Implements hook_init();
 * So all users with the permission 'access coffee' can fire up Coffee
 */
function coffee_init() {
  // only users with the permission access coffee can use coffee
  if (user_access('access coffee')) {
    drupal_add_js(drupal_get_path('module', 'coffee') . '/coffee.js', array('type' => 'file'));
    drupal_add_css(drupal_get_path('module', 'coffee') . '/coffee.css', array('type' => 'file'));
  }

  module_load_include('inc', 'coffee', 'coffee.hooks');
}
